tools_enabled:
    - acl
    - attr
    - autoconf
    - automake
    - bash
    - bc
    - binutils
    - bison
    - bzip2
    - check
    - coreutils
    - dbus
    - dejagnu
    - diffutils
    - e2fsprogs
    
    
    
    
    
    - gcc
    - mpfr
    - gmp
    - mpc
    - linux
    - glibc
    - m4
    - ncurses
    
    - file
    - findutils
    - gawk
    - grep
    - gzip
    - make
    - patch
    - sed
    - tar
    - xz

tools_list:
    acl:
        version: 2.3.1
        url: https://download.savannah.gnu.org/releases/acl/acl-{VERSION}.tar.xz
        patch: false
    attr:
        version: 2.5.1
        url: https://download.savannah.gnu.org/releases/attr/attr-{VERSION}.tar.gz
        patch: false
    autoconf:
        version: 2.71
        url: https://ftp.gnu.org/gnu/autoconf/autoconf-{VERSION}.tar.xz
        patch: false
    automake:
        version: 1.16.5
        url: https://ftp.gnu.org/gnu/automake/automake-{VERSION}.tar.xz
        patch: false
    bash:
        version: 5.2
        url: https://ftp.gnu.org/gnu/bash/bash-{VERSION}.tar.gz
        patch: false
    bc:
        version: 6.0.4
        url: https://github.com/gavinhoward/bc/releases/download/{VERSION}/bc-{VERSION}.tar.xz
        patch: false
    binutils:
        version: 2.39
        url: https://ftp.gnu.org/gnu/binutils/binutils-{VERSION}.tar.xz
        patch: false
    bison:
        version: 3.8.2
        url: https://ftp.gnu.org/gnu/bison/bison-{VERSION}.tar.xz
        patch: false
    bzip2:
        version: 1.0.8
        url: https://www.sourceware.org/pub/bzip2/bzip2-{VERSION}.tar.gz
        patch: false
    check:
        version: 0.15.2
        url: https://www.sourceware.org/pub/bzip2/bzip2-{VERSION}.tar.gz
        patch: false
    coreutils:
        version: 9.1
        url: https://ftp.gnu.org/gnu/coreutils/coreutils-{VERSION}.tar.xz
        patch: https://www.linuxfromscratch.org/patches/lfs/development/coreutils-{VERSION}-i18n-1.patch
    dbus:
        version: 1.14.2
        url: https://dbus.freedesktop.org/releases/dbus/dbus-{VERSION}.tar.xz
        patch: false
    dejagnu:
        version: 1.6.3
        url: https://ftp.gnu.org/gnu/dejagnu/dejagnu-{VERSION}.tar.gz
        patch: false
    diffutils:
        version: 3.8
        url: https://ftp.gnu.org/gnu/diffutils/diffutils-{VERSION}.tar.xz
        patch: false
    e2fsprogs:
        version: 1.46.5
        url: https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.46.5/e2fsprogs-{VERSION}.tar.gz
        patch: false
    
    
    
    
    
    
    
    
        
        
        
    gcc:
        version: 12.1.0
        url: https://ftp.gnu.org/gnu/gcc/gcc-{VERSION}/gcc-{VERSION}.tar.xz
        patch: https://www.linuxfromscratch.org/patches/lfs/development/gcc-{VERSION}-glibc_2.36-1.patch
    mpfr:
        version: 4.1.0
        url: https://ftp.gnu.org/gnu/mpfr/mpfr-{VERSION}.tar.xz
        patch: false
    gmp:
        version: 6.2.1
        url: https://ftp.gnu.org/gnu/gmp/gmp-{VERSION}.tar.xz
        patch: false
    mpc:
        version: 1.2.1
        url: https://ftp.gnu.org/gnu/mpc/mpc-{VERSION}.tar.gz
        patch: false
    linux:
        version: 5.19.1
        url: https://www.kernel.org/pub/linux/kernel/v5.x/linux-{VERSION}.tar.xz
        patch: false
    glibc:
        version: 2.36
        url: https://ftp.gnu.org/gnu/glibc/glibc-{VERSION}.tar.xz
        patch: https://www.linuxfromscratch.org/patches/lfs/development/glibc-{VERSION}-fhs-1.patch
    m4:
        version: 1.4.19
        url: https://ftp.gnu.org/gnu/m4/m4-{VERSION}.tar.xz
        patch: false
    ncurses:
        version: 6.3
        url: https://invisible-mirror.net/archives/ncurses/ncurses-{VERSION}.tar.gz
        patch: false
    
    
    diffutils:
        version: 3.8
        url: https://ftp.gnu.org/gnu/diffutils/diffutils-{VERSION}.tar.xz
        patch: false
    file:
        version: 5.42
        url: https://astron.com/pub/file/file-{VERSION}.tar.gz
        patch: false
    findutils:
        version: 4.9.0
        url: https://ftp.gnu.org/gnu/findutils/findutils-{VERSION}.tar.xz
        patch: false
    gawk:
        version: 5.1.1
        url: https://ftp.gnu.org/gnu/gawk/gawk-{VERSION}.tar.xz
        patch: false
    grep:
        version: 3.7
        url: https://ftp.gnu.org/gnu/grep/grep-{VERSION}.tar.xz
        patch: false
    gzip:
        version: 1.12
        url: https://ftp.gnu.org/gnu/gzip/gzip-{VERSION}.tar.xz
        patch: false
    make:
        version: 4.3
        url: https://ftp.gnu.org/gnu/make/make-{VERSION}.tar.gz
        patch: false
    patch:
        version: 2.7.6
        url: https://ftp.gnu.org/gnu/patch/patch-{VERSION}.tar.xz
        patch: false
    sed:
        version: 4.8
        url: https://ftp.gnu.org/gnu/sed/sed-{VERSION}.tar.xz
        patch: false
    tar:
        version: 1.34
        url: https://ftp.gnu.org/gnu/tar/tar-{VERSION}.tar.xz
        patch: false
    xz:
        version: 5.2.5
        url: https://tukaani.org/xz/xz-{VERSION}.tar.xz
        patch: https://www.linuxfromscratch.org/patches/lfs/development/xz-{VERSION}-upstream_fix-1.patch
